### PR TITLE
Option to add custom text for default linkInfo(header)

### PR DESCRIPTION
**Pull request by saikomal**
### Why are they needed?
This allows users to send an object in the header option with a custom name for available linkInfo.

### CODE REVIEW

**Comment by mlh758** [comment]
This should really have some unit tests with it.

**Comment by fglueck** [comment]
great function

**Comment by saikomal** [comment]
> This should really have some unit tests with it.

**Comment by mlh758** [comment]
Thank you for adding tests. I need to pull this down and try it out but I should have it verified/merged in the next couple of days.

**Comment by mlh758** [comment]
Looks good, merged. Thank you for contributing.

**Pull request merged**
