### PR TITLE
Introduce state class for when any item is selected.

### PR DESCRIPTION
**Pull request by rasben**
### What changes are you proposing?  Why are they needed?
Adding a class to the button when any value is selected.

The usecase of this for me is so I can style the button to have a "placeholder" styling.
Technically it's not a placeholder, but you get the point :)

### Pull Request Approval Checklist:
  - [x] Tests Ran and 0 Failing
>Took 1320 ms to run 334 tests. 334 passed, 0 failed.

  - [ ] Tests Added/Updated
  - [ ] Impacted Demos Updated
  - [ ] Impacted i18n Code Updated

### CODE REVIEW

**Comment by rasben** [comment]
Here's an example of how I'm using it:
Screenshot 2019-03-14 at 19 33 14

The one on the left is selected state, the one on the right is unselected

**Comment by mlh758** [comment]
This looks fine to me. Could you add a test for it?

**Comment by rasben** [comment]
Sure, but can you nudge me in the right direction of where/how I'd add that test? @mlh758 :)

**Comment by mlh758** [comment]
I think an easy way would be to add another expectation to the `checkAll` method [here](https://github.com/ehynds/jquery-ui-multiselect-widget/blob/version3/tests/unit/methods.js#L114).

Just make sure your class is set on it. Then on `uncheckAll` make sure your class is no longer set on it.

**Pull request closed without merging**
