### PR TITLE
Add improvement suggestion as issue type

### PR DESCRIPTION
**Pull request by SteveTheTechie**
### This Pull Request is a
 - [ ] Bug fix
 - [ ] Feature addition
 - [ ] Code refactoring / optimization
 - [ ] Test Addition
 - [ ] Demo Addition
 - [ ] i18n Addition
 - [x] Other (explain below)
 
### Related Issue numbers _(use [Github "keywords"](https://help.github.com/articles/closing-issues-using-keywords/): Fixes #nnn, Closes #nnn, etc.)_
<br>

### What changes are you proposing?  Why are they needed?<br>
_(Provide use cases, code references, [jsfiddle](https://jsfiddle.net/), [codepen](https://codepen.io), etc.)_
Add "improvement suggestion" as an issue type to issue template
  
### @Mentions:
@mlh758

### CODE REVIEW

**Comment by mlh758** [comment]
Wouldn't that just fall under feature request?

**Comment by SteveTheTechie** [comment]
It depends on how you interpret "feature request" I guess.

**Comment by mlh758** [comment]
Yeah, I'm just having a hard time coming up with a suggested improvement that wouldn't be a refactor, bug fix, or a new feature.

Did you have a use case in mind with this one?

**Comment by SteveTheTechie** [comment]
Someone suggesting a new repo branch, someone suggesting a new demo, someone suggesting a new test...  Again, it is just a matter if you consider these new "features" or not.

**Pull request closed without merging**
