### PR TITLE
Better handling of case of both buttonWidth and menuWidth options set to 'auto'

### PR DESCRIPTION
**Pull request by SteveTheTechie**
### This Pull Request is a
 - [ ] Bug fix
 - [x] Feature addition
 - [ ] Code refactoring / optimization
 - [ ] Test Addition
 - [ ] Demo Addition
 - [ ] i18n Addition
 - [ ] Other (explain below)
   
### Related Issue numbers _(use [Github "keywords"](https://help.github.com/articles/closing-issues-using-keywords/): Fixes #nnn, Closes #nnn, etc.)_   

n/a
   
### What changes are you proposing?  Why are they needed?<br>
_(Provide use cases, code references, [jsfiddle](https://jsfiddle.net/), [codepen](https://codepen.io), etc.)_   

Handle case of both buttonWidth and menuWidth options set to 'auto' -- force equal widths.
This improves the automatic width determination if both buttonWidth and menuWidth are set to 'auto'.  
  
### Pull Request Approval Checklist:
  - [x] No Tabs / Code Spacing Consistent
  - [x] Tests Ran and 0 Failing
  - [x] Tests Added/Updated
  - [x] Impacted Demos Updated
  - [x] Impacted i18n Code Updated
  
### @Mentions:
@mlh758

### CODE REVIEW

**Comment by SteveTheTechie** [comment]
@mlh758 

ping

**Comment by mlh758** [comment]
If I open this in the basic demo it seems to have an odd side effect of causing the button height to resize after opening the menu.

image

This isn't present in the base branch. I tested it by changing the initialization code to:
```
$(function(){
   $("select").multiselect({menuWidth: 'auto', buttonWidth: 'auto'});
});
```

**Comment by SteveTheTechie** [comment]
Ok let me take another look.

**Comment by SteveTheTechie** [comment]
@mlh758 I am looking into this.

I also suggest you take a look at this with wrapText: []  (empty array=no wrapping) set.

This tweak widens the button for that case when the menu is opened.

**Pull request closed without merging**
