### PR TITLE
Added option for setting custom menu width

### PR DESCRIPTION
**Pull request by DarkAvanger**
Custom menu width can be used in case of lack of space for select, and long text in options.
Usage: $('select').multiselect({ minWidth: 100, menuWidth:250 });

### CODE REVIEW

**Comment by mlh758** [comment]
I haven't been able to get this to function using the code you provided for usage. The unit tests I wrote are:

    test("menuWidth", function(){
        expect(2);
        var width = 250;
		
        el = $("select").multiselect({ minWidth: 100, menuWidth:width }).multiselect("open");
        equals( menu().parent().find(".ui-multiselect-menu").width(), width, 'width after opening, property set to '+width );
		
        // change height and re-test
        width = 400;
        el.multiselect("option", "menuWidth", width);
        equals( menu().parent().find(".ui-multiselect-menu").width(), width,  'changing value through api to '+width );
		
        el.multiselect("destroy");
	});

No matter what values I put in for width, the menu width still equals the button width.

**Comment by DarkAvanger** [comment]
First of all it is nice to see this old piece of code beign maintained and tested. :)

And as for Your uint test, there are two things: 

1. You have checked width, but what You really should checked is outherWidth.
2. And to see changes in widget You should invoke its refresh method

I have made these adjustments and test below seems to pass.

```
            test("menuWidth", function(){
                expect(2);
                var width = 50;

                el = $("select").multiselect({ minWidth: 100, menuWidth:width }).multiselect("open");

                equals( menu().parent().find(".ui-multiselect-menu").outerWidth(), width, 'width after opening, property set to '+width );

                // change height and re-test
                width = 300;
                el.multiselect("option", "menuWidth", width).multiselect('refresh');
                equals( menu().parent().find(".ui-multiselect-menu").outerWidth(), width,  'changing value through api to '+width );

                el.multiselect("destroy");
            });
```

**Comment by mlh758** [comment]
Well there we go! I'll merge your code when I have a chance and update the
unit tests accordingly. Thank you.

**Comment by mlh758** [comment]
Okay, your code is merged in, and I added your test with it. I'll update the docs to show this new option. Thank you for contributing!

**Pull request merged**
