### PR TITLE
Use JSDoc pretty much everywhere

### PR DESCRIPTION
**Pull request by mlh758**
* Delete the minified files, it will be better to have consumers minify the files themselves or attach them to the tags directly at release
* A bit of code formatting
* Fix a typo in package.json

### CODE REVIEW

**Comment by mlh758** [comment]
@SteveTheTechie Here's a PR that should help with your documentation concerns a bit more thoroughly.

**Comment by SteveTheTechie** [comment]
I am aware of JSDoc, but have not used it.  Maybe there is  reference on it somewhere on the web?  (I will look.)

**Comment by mlh758** [comment]
Here you go: https://google.github.io/styleguide/jsguide.html#jsdoc

**Comment by SteveTheTechie** [comment]
LGTM.    I am presuming that mainly we would mainly be using the `@param and @return` directives.

**Comment by mlh758** [comment]
Mostly, along with the general concept of putting a comment over most methods to give a description of intent and a high level how it's doing it. Especially if it has side effects so there aren't as many surprises to people seeing it for the first time.

**Comment by SteveTheTechie** [comment]
I am still not sure how to document the following options:
```
      disableInputsOnToggle: true,        // (true | false)
      groupColumns: false                 // (true | false)
```

Also, shouldn't the recognized widget-specific event handlers be documented somewhere?  Those are something that it took me a long time to understand--they are buried in the code.

**Comment by SteveTheTechie** [comment]
Are you going to merge this?  I have a few more updates I want to do and I am not sure which branch I should use as the base for the changes.

**Comment by mlh758** [comment]
I'll be merging it soon.

You shouldn't have to worry about the base branch though. You can make your changes off of the version3 branch as you please, and before you open the PR just do
`git rebase <origin>/<branch>` to replay your commits over whatever commits are now in the branch

You'll have to follow it with a:
`git push -f` to overwrite your remote since the history will have diverged.

You can even do those things after opening the PR if other pull requests merge before yours does. It will just change the commits in the PR since the pull request is between branches, not commits.

**Comment by mlh758** [comment]
When you are talking about the events, do you mean [these?](https://github.com/ehynds/jquery-ui-multiselect-widget/wiki/Events)

The options are also [in the wiki](https://github.com/ehynds/jquery-ui-multiselect-widget/wiki/Options) and `disableInputsOnToggle` is mentioned in the JSDoc in the method it applies to in my PR. It's not on the wiki though. Looks like I missed that one.

**Comment by SteveTheTechie** [comment]
> When you are talking about the events, do you mean these?

Yes

**Pull request merged**
