### PR TITLE
Fix #767 - Fix Hover Clipping

### LINKED ISSUE #767: Hover pixel clipping at top and bottom of check boxes
Note to self to fix:   Seeing a few pixels getting clipped off of the hover at the very top and bottom of the check boxes.

### PR DESCRIPTION
**Pull request by SteveTheTechie**
This is a bug fix.

Fixes #767 

Checkboxes UI padding added in css file.
Menu height calcs adjusted to account for padding added.

Unit tests pass.
No new unit tests.
No demos updated.
No i18n files updated.

### CODE REVIEW

**Comment by SteveTheTechie** [comment]
@mlh758 This should be merged after #777 & #778 for best results. This is a branch of #778.

**Comment by SteveTheTechie** [comment]
Will be recreated w/ two commits.

**Comment by mlh758** [comment]
You can just use rebase and then force push back to this branch and it will update the PR. You don't necessarily have to close and make new PRs.

**Comment by SteveTheTechie** [comment]
I do not yet have the whole rebasing thing down...  Still much to learn about git.

**Comment by mlh758** [comment]
1. Checkout branch you want to update
2. `git rebase ehynds/version3` <-- might not be ehynds, whatever you called this remote
  That will replay your current branch onto version3 and make it look like you're PRing in only the new commits.

If histories have diverged (like when I squash all your commits down into one big one, which is what I usually do when I merge your branches)
1. Checkout branch you want to update
2. `git rebase --onto ehynds/version3 HEAD~x` where x is the number of commits you want to keep
  That will pop off the commits you want and replay them onto version3

If you want to squash all your commits into one: `git rebase -i HEAD~x` where x is however many commits you want to combine. You'll get a prompt (probably notepad or vim) that lets you edit what happens to the history. 

All of these rewrite history so you'll have to use `git push -f` to force push your branch. You might want to try them out on backup branches while you get the hang of it since you can lose data with these commands if you accidentally wipe something out. You can actually get that stuff back still using the reflog but that's trickier.

**Comment by SteveTheTechie** [comment]
Keep in mind that I only use the GitHub web interface currently and occasionally the Desktop app for reverts, so while I have a little familiarity w/ the git CLI, I am not sure how to access it. (Using my work computer until I get my personal one fixed or replaced.)  I do have the SmartGit app on my personal laptop... the one that crashed.

**Comment by mlh758** [comment]
Ah, yeah the web interface doesn't provide a lot of those tools.

**Pull request closed without merging**
