### PR TITLE
Hungarian translation

### PR DESCRIPTION
**Pull request by AdamFonagy**
Two translation files are added to i18n directory for Hungarian language.

### CODE REVIEW

**Comment by gs-akhan** [comment]
Hi.. Can you send a PR here at this Repo. I've duplicated this REPO and want to maintain with hellowa strength and focus. I will merge it..
https://github.com/gs-akhan/new-jquery-multiselect-widget
Thanks

**Comment by AdamFonagy** [comment]
Hi there, it has done.
regards,
Adam

**Comment by gs-akhan** [comment]
Thanks.. But you committed on the different REPO. not the one I shared above..
Woops.

**Comment by gs-akhan** [comment]
That;s ok.. lets maintain the forked REPO, instead of a clone..

Cheers

**Comment by AdamFonagy** [comment]
The one you shared cannot be chosen from the list of base repo. I could find the repo I sent the PR to.

**Comment by gs-akhan** [comment]
Cool.. Merged..

**Comment by mlh758** [comment]
@AdamFonagy I can merge this into master for the original now as well. However, in your code I noticed that the description was "German translation" rather than Hungarian. If you fix that I will merge this in.

Thank you for your patience and submitting translations.

**Comment by mlh758** [comment]
I just revisited this and saw the second commit that fixed the name. My apologies, I'll merge this in now.

**Pull request merged**
