### PR TITLE
Escape html characters - optgroup label

### PR DESCRIPTION
**Pull request by enkarito**
To fix issue https://github.com/ehynds/jquery-ui-multiselect-widget/issues/591

### CODE REVIEW

**Comment by gs-akhan** [comment]
Hi.. Can you send a PR here at this Repo. I've duplicated this REPO and want to maintain with hellowa strength and focus. I will merge it..
https://github.com/gs-akhan/new-jquery-multiselect-widget
Thanks

**Comment by mlh758** [comment]
@enkarito It's been quite a while since this was opened. Are you still interested in getting this merged in?

**Comment by gs-akhan** [comment]
+1

**Comment by enkarito** [comment]
@mlh758 Excellent, thank you.

**Pull request merged**
