### PR TITLE
Auto scroll to first selected item in single mode

### PR DESCRIPTION
**Pull request by psyafter**
When menu opened - scroll to first selected item

### This Pull Request is a
 - [ ] Bug fix
 - [V] Feature addition
 - [ ] Code refactoring / optimization
 - [ ] Test Addition
 - [ ] Demo Addition
 - [ ] i18n Addition
 - [ ] Other (explain below)
   
### What changes are you proposing?  Why are they needed?<br>
_(Provide use cases, code references, [jsfiddle](https://jsfiddle.net/), [codepen](https://codepen.io), etc.)_   

  
### Pull Request Approval Checklist:
  - [ ] No Tabs / Code Spacing Consistent
  - [ ] Tests Ran and 0 Failing
  - [ ] Tests Added/Updated
  - [ ] Impacted Demos Updated
  - [ ] Impacted i18n Code Updated

### CODE REVIEW

**Comment by mlh758** [comment]
I checked out this branch, added about a dozen options to the select in the single.htm demo under the `docs` folder. If I scroll down, select an item, close the menu, and open the menu again the menu does not scroll to the selected item. I think the widget is focusing on the first element automatically which causes it to not scroll.

**Comment by psyafter** [comment]
yep, I not tested it without filter.

**Comment by mlh758** [comment]
You don't have to close the PR, just push your commit here once it's fixed and I'll re-evaluate it.

**Comment by mlh758** [comment]
I guess I'll close it since you opened a new one.

**Pull request closed without merging**
