### PR TITLE
Just little changes I had to make to fit my page's requirements

### PR DESCRIPTION
**Pull request by andrehtissot**

### CODE REVIEW

**Comment by mlh758** [comment]
Could you remove the updated min file? I prefer to update those myself so I can verify the changes going into them.

**Comment by andrehtissot** [comment]
I reverted the changes in the minified version as you asked.

**Comment by mlh758** [comment]
I saw, I haven't had a chance to pull these down and test them yet.

**Comment by mlh758** [comment]
Okay, all the unit tests are still working, I verified the changes you made to the keyboard shortcuts are working, and the new options work. They also don't interfere with the `header` option so that's good. I'll go ahead and merge now.

**Pull request merged**
