### PR TITLE
accented characters fixed

### PR DESCRIPTION
**Pull request by LaurentBarbareau**

### CODE REVIEW

**Comment by LaurentBarbareau** [comment]
Do you know that your website is down ?
I get 502 Bad Gateway error on http://www.erichynds.com

**Comment by mlh758** [comment]
Yeah, that's not my website. The original maintainer has moved on from the project and I have no control over his old site.

**Comment by LaurentBarbareau** [comment]
oh, ok. 
on this page too https://github.com/ehynds/jquery-ui-multiselect-widget/wiki/Usage

**Comment by mlh758** [comment]
Thank you, removed the link.

**Pull request merged**
