### PR TITLE
added support for lazy load of multiselect data from ajax/callback

### PR DESCRIPTION
**Pull request by dobozysaurus**
This pull request adds support for loading multiselect data lazily, either via AJAX or a callback function. The data is loaded once the multiselect is clicked on for the first time. The data format is assumed to be JSON, although it would be relatively straightforward to add support for XML datasources as well.

I've added qunit tests for the new functionality as well. Let me know if there's anything that's missing. I've also added a lib - mockjax - which I use to mock ajax calls on the unit tests.

### CODE REVIEW

**Comment by mlh758** [comment]
@dobozysaurus I've been going through the pull requests looking to merge in useful changes. Is this something you would still like to bring into the library? I can definitely see a use case for this.

**Comment by SteveTheTechie** [comment]
I think this needs more discussion.   It seems like the OP is wanting to use AJAX implementation code that may duplicate available jQuery functionality.  

Additionally, if the multi-select is being created from JSON, does that imply that an underlying native select is not needed?   If a select is still needed, then the native select would need to be updated from the JSON, as well.

**Comment by mlh758** [comment]
Yeah I've been sitting on this one for a long time because I like the idea of being able to use Ajax or some other callback to provide data after page load.

`select2` has a feature like this where you provide an Ajax call to make, and it expects the reply to be a json of values and displays. In our case, we could use that to build options into the underlying select and then call `refresh`.  I would prefer not to abandon the select.

**Comment by mlh758** [comment]
I'm going to go ahead and close this one since we're discussing implementing it in version3.

**Pull request closed without merging**
